apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-dep
  labels:
    app: node-demo-app
spec:
  selector:
    matchLabels:
      app: node-demo-app
  replicas: 1
  template:
    metadata:
      labels:
        app: node-demo-app
    spec:
      containers:
      - name: node
        image: howmun/jenkins-docker-example:$BUILD_NUMBER
        ports:
        - containerPort: 3000